#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: all

users:
    - default

runcmd:
    - sleep 10
    - [ sh, -c, "until ping -c1 www.centos.org &>/dev/null; do :; done" ]
    - [ sh, -c, "until ping -c1 www.docker.com &>/dev/null; do :; done" ]
    - [ sh, -c, "until ping -c1 www.google.com &>/dev/null; do :; done" ]
    - [ sh, -c, "sudo yum clean all" ]
    - [ sh, -c, "sudo yum update -y" ]
    - [ sh, -c, "sudo yum install -y epel-release" ]
    - [ sh, -c, "sudo yum install -y salt-master" ]
    - [ sh, -c, "sudo systemctl enable salt-master &&  sudo systemctl start salt-master" ]
